apiVersion: v2
description: Kong Cloud Template Chart
engine: gotpl
home: https://konghq.com
maintainers:
- name: ttyS0e
  email: jack.tysoe@konghq.com
name: kong
sources:
version: 1.0.0
appVersion: "2.8"
dependencies:
- name: kong
  version: 2.9.1  # keep this in line with the latest tag at https://github.com/Kong/charts
  repository: https://charts.konghq.com
