{{- if .Values.secretsProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kong-secrets-class
  namespace: {{ .Release.Namespace }}
spec:
  parameters:
    objects: |
      - objectName: "POSTGRES_PASSWD"
        secretPath: "secret/data/{{ .Values.secretsProviderClass.secretPath }}"
        secretKey: "POSTGRES_PASSWD"
      - objectName: "POSTGRES_USER"
        secretPath: "secret/data/{{ .Values.secretsProviderClass.secretPath }}"
        secretKey: "POSTGRES_USER"
    roleName: kong
    vaultAddress: "{{ .Values.secretsProviderClass.vaultAddress }}"
  provider: vault
  secretObjects:
  - data:
    - key: POSTGRES_PASSWD
      objectName: POSTGRES_PASSWD
    - key: POSTGRES_USER
      objectName: POSTGRES_USER
    secretName: kong-secrets-class
    type: Opaque
{{- end }}